-- D1 反馈系统建表（干净版，无大段注释，控制台直接粘贴执行）
CREATE TABLE IF NOT EXISTS feedback (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content TEXT NOT NULL,
  createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  adminReply TEXT DEFAULT '',
  isPublic INTEGER DEFAULT 0,
  deviceId TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS notice (
  id INTEGER PRIMARY KEY,
  content TEXT NOT NULL DEFAULT '',
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  deviceId TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
